version: '3.5'
services:
  minio_jhosep:
    container_name: minio_server_new
    image: minio/minio:RELEASE.2022-04-29T01-27-09Z
    volumes:
      - /mnt/miniodata:/Data
      - /mnt/ssl:/root/.minio/certs/CAs
    command: server /Data --console-address ":9001" 
    ports:
      - '8530:9000'
      - '8531:9001'
    environment:
      - MINIO_ROOT_USER=123wasd
      - MINIO_ROOT_PASSWORD=123wasd@wasd
    restart: always